---
- name: setup of jenkins reqiured softwares
  hosts: jenkins
  tasks:
    - name: install jenkins and required softwares
      apt: 
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: openjdk-11-jdk,b: yes}
        - {a: git,b: no}
        - {a: maven,b: no}
    - name: download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.387.3/jenkins.war
        dest: /home/ubuntu
- name: tomcat installation on servers
  hosts: servers
  tasks:
   - name: install tomcat9
     apt: 
       name: "{{item.a}}"
       state: present
       update_cache: "{{item.b}}"
     with_items:
        - {a: tomcat9,b: yes}
        - {a: tomcat9-admin,b: yes}
   - name: copy tomcat-users.xml 
     copy:
       src: /home/ubuntu/tomcat-users.xml
       dest: /etc/tomcat9     
   - name: change port on 8080 to 9090
     replace: 
       regexp: 8080
       replace: 9090
       path: /etc/tomcat9/server.xml
     notify: restart tomcat9
  handlers:    
   - name: restart tomcat9
     service:
       name: tomcat9
       state: restarted     
        

...
