---
- name: install firewalld using host scope variables
  hosts: servers
  tasks:
    - name: install firewalld
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"




...          
