---
- name: configure tomcat9
  hosts: all 
  tasks:
    - name: configure tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: configure tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present
        update_cache: no
    - name: copy tomcat-users.xml
      copy:
        src: /home/ubuntu/tomcat-users.xml
        dest: /etc/tomcat9
    - name: change port from 9090 to 8080
      replace:
        regexp: 9090
        replace: 8080
        path: /etc/tomcat9/server.xml
    - name: restart tomcat9 
      service: 
        name: tomcat9
        state: restarted
    - name: pause for 1 min
      pause:
        minutes: 1
    - name: check url response
      uri: 
        url: http://54.190.38.178:8080
        status_code: 200
    - name: check url response
      uri:
        url: http://34.219.55.122:8080
        status_code: 200

...

