---
- name: configure appche2
  hosts: all
  tasks:
    - name: configuration on apache2
      apt: 
        name: apache2
        state: present
        update_cache: yes
    - name: edit the apache2 html file
      copy:    
        content: "Eagle eye security systems"
        dest: /var/www/html/index.html 
    - name: restart apache2
      service: 
        name: apache2
        state: restarted
    - name: chcek url response
      uri:
        url: http://54.190.38.178
        status_code: 200
    - name: chcek url response
      uri:
        url: http://34.219.55.122
        status_code: 200
       
