---
- name: check if the file is executable permissions or not if it is yes delete it
  hosts: all
  tasks: 
     - name: check if the file10 
       stat:
         path: /home/ubuntu/file10
       register: b    
     - name: display the output above module
       debug: 
          var: b
     - name: if  the file have executable permissions delete it
       file:
         name: /home/ubuntu/file10
         state: absent
       when: b.stat.executable == true  

...         
